#!/bin/bash

# Hide "last login" line when starting a new terminal session
touch $HOME/.hushlogin

# Install zsh
echo 'Install oh-my-zsh'
echo '-----------------'
rm -rf $HOME/.oh-my-zsh
curl -L https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh | sh

# Add global gitignore
ln -s $HOME/.dotfiles/shell/.global-gitignore $HOME/.global-gitignore
git config --global core.excludesfile $HOME/.global-gitignore

# Symlink zsh prefs
rm $HOME/.zshrc
ln -s $HOME/.dotfiles/shell/.zshrc $HOME/.zshrc

# Symlink vim prefs
rm $HOME/.vimrc
ln -s $HOME/.dotfiles/shell/.vimrc $HOME/.vimrc
rm $HOME/.vim
ln -s $HOME/.dotfiles/shell/.vim $HOME/.vim

# Fix missing font characters (see https://github.com/robbyrussell/oh-my-zsh/issues/1906)
cd ~/.oh-my-zsh/themes/
git checkout d6a36b1 agnoster.zsh-theme

# Activate z
cd ~/.dotfiles/shell
chmod +x z.sh

echo 'Install homebrew'
echo '----------------'
echo install homebrew
sudo rm -rf /usr/local/Cellar /usr/local/.git && brew cleanup
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
echo 'eval "$(/opt/homebrew/bin/brew shellenv)"' >> $HOME/.zprofile
eval "$(/opt/homebrew/bin/brew shellenv)"

echo 'Install pkg-config'
echo '------------------'
brew install pkg-config

echo 'Install wget'
echo '------------'
brew install wget

echo 'Install httpie'
echo '--------------'
brew install httpie

echo 'Install ncdu'
echo '------------'
brew install ncdu

echo 'Install hub'
echo '-----------'
brew install hub

echo 'Install ack'
echo '-----------'
brew install ack

echo 'Install doctl'
echo '-------------'
brew install doctl

echo 'Install git secret'
echo '------------------'
brew install git-secret

echo 'Install some nice quicklook plugins'
echo '-----------------------------------'
brew install --cask qlcolorcode qlstephen qlmarkdown quicklook-json qlprettypatch quicklook-csv suspicious-package

echo 'Install zsh-autosuggestions'
echo '---------------------------'
brew install zsh-autosuggestions

echo 'Install warp'
echo '---------------------------'
brew install --cask warp

echo 'Install ray'
echo '---------------------------'
brew install --cask ray

echo 'Install helo'
echo '---------------------------'
brew install --cask helo

echo 'Install setapp'
echo '---------------------------'
brew install --cask setapp

echo 'Install nordvpn'
echo '---------------------------'
brew install --cask nordvpn

echo 'Install docker'
echo '---------------------------'
brew install --cask docker

echo 'Install tuple'
echo '---------------------------'
brew install --cask tuple

echo 'Install raycast'
echo '---------------------------'
brew install --cask raycast

echo 'Install slack'
echo '---------------------------'
brew install --cask slack

echo 'Install visual-studio-code'
echo '---------------------------'
brew install --cask visual-studio-code

echo 'Install jetbrains-toolbox'
echo '---------------------------'
brew install --cask jetbrains-toolbox

echo 'Install 1password'
echo '---------------------------'
brew install --cask 1password

echo 'Install dbngin'
echo '---------------------------'
brew install --cask dbngin

echo 'Install insomnia'
echo '---------------------------'
brew install --cask insomnia

echo 'Install google-chrome'
echo '---------------------------'
brew install --cask google-chrome

echo 'Install MySQL client'
echo '---------------------------'
brew install mysql-client

echo 'Install AWS CLI'
echo '---------------------------'
brew install awscli

echo 'Install JQ'
echo '---------------------------'
brew install jq

echo 'Install php'
echo '-----------'
brew install php

echo 'Install composer'
echo '----------------'
brew install composer

echo 'Install aicommits'
echo '-----------------'
npm install -g aicommits

echo 'Install xdebug'
echo '--------------'
pecl install xdebug

echo 'Install redis'
echo '-------------'
pecl install redis

echo 'Install phpunit-watcher'
echo '-----------------------'
composer global require spatie/phpunit-watcher

echo 'Install laravel valet'
echo '---------------------'
composer global require laravel/valet
valet install
valet loopback 10.254.254.254

if [ -f ./proxies.sh]
    chmod +x proxies.sh
    /bin/bash ./proxies.sh
fi

echo 'Install nvm'
echo '-----------------------'
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash

echo 'Install node 20'
echo '-----------------------'
nvm install 20

echo '++++++++++++++++++++++++++++++'
echo '++++++++++++++++++++++++++++++'
echo 'All done!'
echo 'Things to do to make the agnoster terminal theme work:'
echo '1. Install menlo patched font included in ~/.dotfiles/misc https://gist.github.com/qrush/1595572/raw/Menlo-Powerline.otf'
echo '2. Install patched solarized theme included in ~/.dotfiles/misc'

echo '++++++++++++++++++++++++++++++'
echo 'Some optional tidbits'

echo '1. Make sure dropbox is running first. If you have not backed up via Mackup yet, then run `mackup backup` to symlink preferences for a wide collection of apps to your dropbox. If you already had a backup via mackup run `mackup restore` You'\''ll find more info on Mackup here: https://github.com/lra/mackup.'
echo '2. Set some sensible os x defaults by running: $HOME/.dotfiles/macos/set-defaults.sh'
echo '3. Make a .dotfiles-custom/shell/.aliases for your personal commands'

echo '++++++++++++++++++++++++++++++'
echo '++++++++++++++++++++++++++++++'
